name: ci-linux

on:
  push:
    branches: [ main, chore/merge-integrity-audit ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Linux Audit
        run: |
          chmod +x ./scripts/audit/scan.sh || true
          ./scripts/audit/scan.sh .

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Frontend checks (if package.json exists at repo root)
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          npm ci
          npm run typecheck --if-present
          npm run lint --if-present
          npm test --if-present

      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-audit-and-tests
          path: |
            artifacts/audit/**
            **/TestResults/**/*.trx

