name: ci-windows

on:
  push:
    branches: [ main, chore/merge-integrity-audit ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Windows Audit
        shell: pwsh
        run: |
          pwsh -File .\scripts\audit\scan.ps1

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Smoke Render
        shell: pwsh
        run: |
          pwsh -File .\scripts\run_quick_generate_demo.ps1 -FfmpegPath ".\scripts\ffmpeg\ffmpeg.exe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-audit-smoke-and-tests
          path: |
            artifacts/**
            **/TestResults/**/*.trx

