name: No placeholders allowed

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for placeholder text with audit script
        run: |
          pwsh scripts/audit/no_future_text.ps1
        shell: pwsh
